 INSERT INTO jobTinder_pais(id, nome)
VALUES (1, 'ARGENTINA'),
(2, 'BOLÍVA'),
(3, 'BRASIL'),
(4, 'CHILE'),
(5, 'COLÔMBIA'),
(6, 'EQUADOR'),
(7, 'GUIANA'),
(8, 'PARAGUAI'),
(9, 'PERU'),
(10, 'SURINAME'),
(11, 'URUAGUAI'),
(12, 'VENEZUELA');

SELECT * FROM jobTinder_pais

INSERT INTO jobTinder_estado (id, nome, sigla, pais_id) VALUES
(1, 'Acre', 'AC', 3),
(2, 'Alagoas', 'AL', 3),
(3, 'Amazonas', 'AM', 3),
(4, 'Amapá', 'AP', 3),
(5, 'Bahia', 'BA', 3),
(6, 'Ceará', 'CE', 3),
(7, 'Distrito Federal', 'DF', 3),
(8, 'Espírito Santo', 'ES', 3),
(9, 'Goiás', 'GO', 3),
(10, 'Maranhão', 'MA', 3),
(11, 'Minas Gerais', 'MG', 3),
(12, 'Mato Grosso do Sul', 'MS', 3),
(13, 'Mato Grosso', 'MT', 3),
(14, 'Pará', 'PA', 3),
(15, 'Paraíba', 'PB', 3),
(16, 'Pernambuco', 'PE', 3),
(17, 'Piauí', 'PI', 3),
(18, 'Paraná', 'PR', 3),
(19, 'Rio de Janeiro', 'RJ', 3),
(20, 'Rio Grande do Norte', 'RN', 3),
(21, 'Rondônia', 'RO', 3),
(22, 'Roraima', 'RR', 3),
(23, 'Rio Grande do Sul', 'RS', 3),
(24, 'Santa Catarina', 'SC', 3),
(25, 'Sergipe', 'SE', 3),
(26, 'São Paulo', 'SP', 3),
(27, 'Tocantins', 'TO', 3);

SELECT * FROM jobTinder_estado;

INSERT INTO jobTinder_cidade (id, nome, estado_id) VALUES
(1, 'Afonso Cláudio', 8),
(2, 'Água Doce do Norte', 8),
(3, 'Águia Branca', 8),
(4, 'Alegre', 8),
(5, 'Alfredo Chaves', 8),
(6, 'Alto Rio Novo', 8),
(7, 'Anchieta', 8),
(8, 'Apiacá', 8),
(9, 'Aracruz', 8),
(10, 'Atilio Vivacqua', 8),
(11, 'Baixo Guandu', 8),
(12, 'Barra de São Francisco', 8),
(13, 'Boa Esperança', 8),
(14, 'Bom Jesus do Norte', 8),
(15, 'Brejetuba', 8),
(16, 'Cachoeiro de Itapemirim', 8),
(17, 'Cariacica', 8),
(18, 'Castelo', 8),
(19, 'Colatina', 8),
(20, 'Conceição da Barra', 8),
(21, 'Conceição do Castelo', 8),
(22, 'Divino de São Lourenço', 8),
(23, 'Domingos Martins', 8),
(24, 'Dores do Rio Preto', 8),
(25, 'Ecoporanga', 8),
(26, 'Fundão', 8),
(27, 'Governador Lindenberg', 8),
(28, 'Guaçuí', 8),
(29, 'Guarapari', 8),
(30, 'Ibatiba', 8),
(31, 'Ibiraçu', 8),
(32, 'Ibitirama', 8),
(33, 'Iconha', 8),
(34, 'Irupi', 8),
(35, 'Itaguaçu', 8),
(36, 'Itapemirim', 8),
(37, 'Itarana', 8),
(38, 'Iúna', 8),
(39, 'Jaguaré', 8),
(40, 'Jerônimo Monteiro', 8),
(41, 'João Neiva', 8),
(42, 'Laranja da Terra', 8),
(43, 'Linhares', 8),
(44, 'Mantenópolis', 8),
(45, 'Marataízes', 8),
(46, 'Marechal Floriano', 8),
(47, 'Marilândia', 8),
(48, 'Mimoso do Sul', 8),
(49, 'Montanha', 8),
(50, 'Mucurici', 8),
(51, 'Muniz Freire', 8),
(52, 'Muqui', 8),
(53, 'Nova Venécia', 8),
(54, 'Pancas', 8),
(55, 'Pedro Canário', 8),
(56, 'Pinheiros', 8),
(57, 'Piúma', 8),
(58, 'Ponto Belo', 8),
(59, 'Presidente Kennedy', 8),
(60, 'Rio Bananal', 8),
(61, 'Rio Novo do Sul', 8),
(62, 'Santa Leopoldina', 8),
(63, 'Santa Maria de Jetibá', 8),
(64, 'Santa Teresa', 8),
(65, 'São Domingos do Norte', 8),
(66, 'São Gabriel da Palha', 8),
(67, 'São José do Calçado', 8),
(68, 'São Mateus', 8),
(69, 'São Roque do Canaã', 8),
(70, 'Serra', 8),
(71, 'Sooretama', 8),
(72, 'Vargem Alta', 8),
(73, 'Venda Nova do Imigrante', 8),
(74, 'Viana', 8),
(75, 'Vila Pavão', 8),
(76, 'Vila Valério', 8),
(77, 'Vila Velha', 8),
(78, 'Vitória', 8);

SELECT * FROM jobTinder_cidade;

