# Generated by Django 2.1.7 on 2019-05-22 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('experiencia', models.TextField(max_length=280)),
                ('habilidades', models.TextField(max_length=50)),
                ('local_preferencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Empresa')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('dataHora', models.DateTimeField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Candidato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PreMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('calcCompatibilidade', models.IntegerField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Recrutador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Filial')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='VagaEmprego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('regimeTrabalho', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('requisitosObrigatorios', models.CharField(max_length=100)),
                ('requisitosDesejaveis', models.CharField(max_length=100)),
                ('qtdVaga', models.IntegerField()),
                ('disponibilidade', models.BooleanField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='prematch',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.VagaEmprego'),
        ),
        migrations.AddField(
            model_name='match',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.VagaEmprego'),
        ),
        migrations.AddField(
            model_name='chat',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Empresa'),
        ),
        migrations.AddField(
            model_name='chat',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Filial'),
        ),
        migrations.AddField(
            model_name='chat',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Match'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Endereco'),
        ),
    ]
