# Generated by Django 2.1.7 on 2019-06-22 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('localPreferencia', models.CharField(max_length=50)),
                ('trabalhosPassados', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.FloatField()),
                ('areaConhecimento', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaoSocial', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=20)),
                ('rua', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Empresa')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField()),
                ('data', models.DateField()),
                ('dataExpiracao', models.DateField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('mensagem', models.CharField(max_length=50)),
                ('statusRemetente', models.CharField(max_length=30)),
                ('statusDestinatario', models.CharField(max_length=30)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Candidato')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recrutador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Endereco')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Filial')),
            ],
        ),
        migrations.CreateModel(
            name='VagaEmprego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField()),
                ('status', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=50)),
                ('remuneracao', models.CharField(max_length=50)),
                ('cargaHoraria', models.IntegerField()),
                ('dataCriacao', models.DateField()),
                ('regimeTrabalho', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Cidade')),
                ('recrutador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Recrutador')),
            ],
        ),
        migrations.AddField(
            model_name='mensagem',
            name='recrutador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Recrutador'),
        ),
        migrations.AddField(
            model_name='match',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.VagaEmprego'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Pais'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Estado'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='competencias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Competencias'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Endereco'),
        ),
    ]
