# Generated by Django 2.1.8 on 2019-04-10 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=20)),
                ('CPF', models.CharField(max_length=50)),
                ('dataNascimento', models.DateField()),
                ('localPreferencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=20)),
                ('CNPJ', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEP', models.CharField(max_length=20)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('dataHora', models.DateTimeField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Candidato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PreMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('calcCompatibilidade', models.IntegerField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Candidato')),
            ],
        ),
        migrations.CreateModel(
            name='VagaEmprego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('regimeTrabalho', models.CharField(max_length=100)),
                ('dataPublicacao', models.DateField()),
                ('requisitos', models.CharField(max_length=100)),
                ('qtdVaga', models.IntegerField()),
                ('disponibilidade', models.BooleanField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='prematch',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.VagaEmprego'),
        ),
        migrations.AddField(
            model_name='match',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.VagaEmprego'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Endereco'),
        ),
        migrations.AddField(
            model_name='chat',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Empresa'),
        ),
        migrations.AddField(
            model_name='chat',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Match'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Endereco'),
        ),
    ]
