# Generated by Django 2.1.7 on 2019-06-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobTinder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagaemprego',
            name='status',
        ),
    ]
