# Generated by Django 2.1.7 on 2019-06-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobTinder', '0002_remove_vagaemprego_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='competencias',
        ),
        migrations.AddField(
            model_name='competencias',
            name='candidato',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jobTinder.Candidato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competencias',
            name='vagaEmprego',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jobTinder.VagaEmprego'),
            preserve_default=False,
        ),
    ]
