# Generated by Django 2.1.7 on 2019-06-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobTinder', '0003_auto_20190623_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nomeFantasia',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vagaemprego',
            name='titulo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vagaemprego',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vagaemprego',
            name='regimeTrabalho',
            field=models.CharField(max_length=500),
        ),
    ]
