# Generated by Django 2.1.7 on 2019-06-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobTinder', '0004_auto_20190624_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencias',
            name='candidato',
        ),
        migrations.RemoveField(
            model_name='competencias',
            name='vagaEmprego',
        ),
    ]
